README.md
#What
メルカリクローンサイトのDB設計ができましたのでレビューをお願い致します。
#Why
メルカリクローンサイトをのデータベースを作成するため。
=> READMEプルリクエスト

README.md
#What
READMEのレビューをお願い致します。
#Why
メルカリサイトのDB設計のため。
=> READMEプルリクエスト２

config/unicorn.rb
listen 3000
↓以下のように修正
listen "#{app_path}/tmp/sockets/unicorn.sock"
=> Unicorn.rb編集

Capfile, config/deploy.rb, config/deploy/production.rb, config/deploy/staging.rb, config/environments/production.rb, config/unicorn.rb
自動デプロイ機能の導入
・ファイル作成
・Unicorn.deploy他ファイル編集
=> 自動デプロイ機能編集　ito

Gemfile, Gemfile.lock, app/assets/stylesheets/_products.scss, app/assets/stylesheets/application.scss, app/controllers/products_controller.rb, app/views/products/index.html.haml
#what
アイコン表示。
#why
アイコンを表示させるため
=> gemインストールしました

app/assets/stylesheets/application.scss, app/assets/stylesheets/products/_new.scss, app/assets/stylesheets/products/_products.scss, app/views/products/_footer.html.haml, app/views/products/_header.html.haml, app/views/products/index.html.haml, app/views/products/mercariformat.html.haml, app/views/products/new.html.haml, config/database.yml
#what
商品購入ページのマークアップ実施
#way
ビューはproducts/new.html.haml
cssはproducts/_new.scss
に記載しました。
=> 商品購入確認ページマークアップ

README.md, db/migrate/20191104055632_add_phone_number_to_users.rb, db/schema.rb
#What  DB設計の微修正
usersカラムへphonenumberの追加
#Why
ユーザー登録画面に考慮したDB設計をするため
=> usersカラムへphonenumberの追加

Gemfile, Gemfile.lock
#What
下記のgetfileの追加を行いました。
gem 'jquery-rails'
gem 'jquery-ui-rails' 
gem 'active_hash'
gem 'ancestry'
gem 'gretel'
gem 'payjp'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2'
#Why
今後使用するgemを導入するため。
=> getfileの追加

README.md, app/models/brand.rb, app/models/card.rb, app/models/category.rb, db/migrate/20191104110036_create_brands.rb, db/migrate/20191105030454_create_categories.rb, db/migrate/20191105033847_create_cards.rb, db/schema.rb, spec/models/brand_spec.rb, spec/models/card_spec.rb, spec/models/category_spec.rb
#What
テーブルやモデルを作成しました。
#Why
brand category caedテーブル作成のため
=> テーブル作成（migrationファイルやmodel、readme変更）

README.md, app/assets/javascripts/pays.coffee, app/assets/stylesheets/pays.scss, app/controllers/pays_controller.rb, app/helpers/pays_helper.rb, app/models/pay.rb, db/migrate/20191105043334_create_pays.rb, db/schema.rb, spec/controllers/pays_controller_spec.rb, spec/helpers/pays_helper_spec.rb, spec/models/pay_spec.rb
#What
paysテーブル、コントローラー、モデルを作成しました。
#why
pay.jpの導入とユーザー登録作業を進めやすくするため。
=> paysテーブル、コントローラー、モデルの作成

README.md, app/assets/javascripts/products.coffee, app/models/image.rb, app/models/product.rb, db/migrate/20191105052509_create_products.rb, db/migrate/20191105060400_create_images.rb, db/schema.rb, spec/controllers/products_controller_spec.rb, spec/helpers/products_helper_spec.rb, spec/models/image_spec.rb, spec/models/product_spec.rb
#What
出品テーブル、画像　モデル追加とそれに伴いDBの見直としREADME修正。
#Why
商品出品ページ作成のため。
=> 出品テーブル、画像　モデル追加DBの見直しREADME修正

app/controllers/signup_controller.rb, app/models/user.rb, app/views/layouts/application.html.haml, app/views/signup/_progress.html.haml, app/views/signup/done.html.haml, app/views/signup/step1.html.haml, app/views/signup/step2.html.haml, app/views/signup/step3.html.haml, app/views/signup/step4.html.haml
=> Step2サーバーサイド実装

README.md, app/controllers/signup_controller.rb, app/views/signup/step3.html.haml, db/migrate/20191106040827_change_datatype_phone_number_of_user.rb, db/migrate/20191106053358_change_column_to_pyment_methodow_null.rb, db/schema.rb
＃what
データベース２件追加し、名前だけ登録できるようにしました。
=> ステップ４登録画面実装

app/controllers/application_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/controllers/users/registrations_controller.rb, app/models/user.rb, app/views/devise/sessions/new.html.haml, app/views/signup/entry_signin.html.haml, app/views/signup/entry_signup.html.haml, config/initializers/devise.rb, config/routes.rb
#what
グーグルとフェイスブックのaminiauth実装。
シークレットキー設定。
devise_forを設定。
コールバック先のURLに変更。
ログイン機能実装。
#why
view/signup/entry_signin
ビューを設定。
models/user.rb
config/routes.rb
initializers/devise.rb
以上に詳細を記載しました。
=> ominiauth実装。

app/assets/stylesheets/users/_logout.scss, app/views/users/_logout.html.haml, db/schema.rb
=> ログアウト機能の実装＿伊藤

app/views/products/show.html.haml, app/views/products/showmine.html.haml
=> 商品詳細情報転移＿伊藤

app/controllers/pays_controller.rb, app/controllers/signup_controller.rb, db/migrate/20191115040800_change_data_card_id_to_pay.rb, db/schema.rb
#what
paysテーブルのcard_idをstring型に変更
integer型だと９けた以上のデータが保存されず、０が入ってしまうため
=> card_idをstring型に変更

app/assets/stylesheets/modules/topfooter.scss, app/assets/stylesheets/products/_show.scss, app/views/products/show.html.haml, app/views/products/showmine.html.haml, app/views/users/_userside.html.haml, app/views/users/listing.html.haml, config/breadcrumbs.rb
=> トップページビュー変更＿伊藤

app/controllers/application_controller.rb, config/deploy.rb, config/deploy/production.rb
=> Basic認証導入＿伊藤

app/uploaders/image_uploader.rb, config/deploy.rb, config/initializers/carrierwave.rb
=> S3への分岐導入_伊藤

app/controllers/products_controller.rb, app/controllers/users_controller.rb, app/views/users/_listing.html.haml, app/views/users/_userside.html.haml, app/views/users/listing.html.haml, config/breadcrumbs.rb, config/routes.rb
=> listingコントローラーの不具合微修正
